# Generated by Django 5.2.5 on 2026-05-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0019_remove_interviewsession_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('AP', 'APPROVED'), ('RE', 'REJECTED'), ('PE', 'PENDING')], default='AP', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
