# Generated by Django 5.2.5 on 2026-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0020_company_is_verified_jobposting_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('AP', 'APPROVED'), ('RE', 'REJECTED'), ('PE', 'PENDING')], default='PE', max_length=2),
        ),
    ]
