# Generated by Django 5.2.5 on 2026-05-18 04:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0021_remove_company_is_verified_alter_company_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'công ty', 'verbose_name_plural': 'Công ty'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'hóa đơn', 'verbose_name_plural': 'Hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'bài ứng tuyển', 'verbose_name_plural': 'Bài ứng tuyển'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'verbose_name': 'bài đăng', 'verbose_name_plural': 'Bài đăng'},
        ),
        migrations.AlterModelOptions(
            name='jobpostingfee',
            options={'verbose_name': 'mức phí', 'verbose_name_plural': 'Phí đăng bài'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('AP', 'CHẤP NHẬN'), ('RE', 'TỪ CHỐI'), ('PE', 'ĐANG CHỜ DUYỆT')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='jobapis.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1778378415/mdxku1ihvvwkfdewxveb.jpg', max_length=255, null=True),
        ),
    ]
